"""Fail if a committed notebook carries execution output.

Notebook outputs are how a repository accidentally grows tens of megabytes of
base64 PNG, and how a figure in version control drifts from the code that made
it. Every figure here is regenerated by `pertreadout figures`.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

tracked = subprocess.run(
    ["git", "ls-files", "*.ipynb"], capture_output=True, text=True, check=True
).stdout.split()

problems = []
for name in tracked:
    nb = json.loads(Path(name).read_text())
    dirty = [
        i
        for i, cell in enumerate(nb.get("cells", []))
        if cell.get("outputs") or cell.get("execution_count") is not None
    ]
    if dirty:
        problems.append(f"{name}: cells {dirty} carry output; strip before committing")

if problems:
    print("\n".join(problems), file=sys.stderr)
    sys.exit(1)
print(f"{len(tracked)} notebooks clean")
